"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['calculator.py']
DATA_FILES = []
OPTIONS = {
    'includes': ('python-dateutil', 'tkinter', 'datetime', 'calendar'),
    'iconfile': 'image.png'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    author='Yuliia Fedorchenko',
    author_email='julia.fdrchnk@gmail.com',
    setup_requires=['py2app'],
)
